// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mugectvlobgzyonzcmme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11Z2VjdHZsb2JnenlvbnpjbW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTUzOTIsImV4cCI6MjA3Mjc5MTM5Mn0.Q1-XviJ-4ODeTRQbniuYtv15lL9jn_oMhFQlUi9HZcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});